name: Build OpenJDK for Android aarch32

on: [push]

jobs:
  build:
    strategy:
      matrix:
        arch: [ "aarch32", "aarch64", "x86", "x86_64" ]
      fail-fast: false

    name: "Build ${{matrix.arch}}"
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7

    - name: Build with CI build script
      run: bash "ci_build_arch_${{matrix.arch}}.sh"

    - name: Upload JDK build output
      uses: actions/upload-artifact@v2
      with:
        name: "jdk8-${{matrix.arch}}"
        path: jdk8*.tar.xz

    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre8-${{matrix.arch}}'
        path: jre8*.tar.xz

    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v2
      with:
        name: "jre8-debuginfo-${{matrix.arch}}"
        path: dizout
