name: Build OpenJDK for Android

on: [push, pull_request, workflow_dispatch]

jobs:
  build_iosport:
    name: "Build for iOS aarch64"
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7

    - name: Build with CI build script
      run: |
        export BUILD_IOS=1
        bash "ci_build_arch_aarch64.sh"
    - name: Upload JDK build output
      uses: actions/upload-artifact@v2
      with:
        name: "jdk8-ios-${{matrix.arch}}"
        path: jdk8*.tar.xz

    - name: Upload JRE build output
      uses: actions/upload-artifact@v2
      with:
        name: 'jre8-ios-${{matrix.arch}}'
        path: jre8*.tar.xz

    - name: Upload JRE debuginfo build output
      uses: actions/upload-artifact@v2
      with:
        name: "jre8-ios-debuginfo-${{matrix.arch}}"
        path: dizout
  pojav:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Get jre8-aarch32
      uses: actions/download-artifact@v2
      with:
        name: jre8-aarch32
        path: pojav
    - name: Get jre8-aarch64
      uses: actions/download-artifact@v2
      with:
        name: jre8-aarch64
        path: pojav
    - name: Get jre8-x86
      uses: actions/download-artifact@v2
      with:
        name: jre8-x86
        path: pojav
    - name: Get jre8-x86_64
      uses: actions/download-artifact@v2
      with:
        name: jre8-x86_64
        path: pojav
    - name: Repack JRE
      run: bash "repackjre.sh" $GITHUB_WORKSPACE/pojav $GITHUB_WORKSPACE/pojav/jre8-pojav
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
          name: jre8-pojav
          path: pojav/jre8-pojav/*
