name: Build OpenJDK for Android aarch64

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: set up JDK 1.7
      uses: actions/setup-java@v1
      with:
        java-version: 1.7

    - name: Build with CI build script
      run: bash ci_build_arch_aarch64.sh

    - name: Upload build output
      uses: actions/upload-artifact@v2
      with:
        # name: jre
        path: jre*.tar.xz
